fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"

# profile module layout, default include ntp module
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    powershell: "https://github.com/puppetlabs/puppetlabs-powershell.git"
    firewall: "https://github.com/gildas/puppet-firewall.git"
    winntp: "https://github.com/puppetlabs/tse-module-winntp.git"
    registry: "https://github.com/puppetlabs/puppetlabs-registry.git"
    windows_sql: "https://github.com/insentia/windows_sql.git"
    windows_isos: "https://github.com/insentia/windows_isos.git"

  symlinks:
    profile_mssql: "#{source_dir}"
